language: python
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - binutils

python:
  - 3.6

env:
  matrix:
   - JLIST_UBSAN=0
   - JLIST_UBSAN=1

install:
  - pip install -r etc/requirements-dev.txt
  - JLIST_UBSAN=$JLIST_UBSAN CC=gcc-8 CXX=g++-8 pip install -e .

script:
  - nosetests jlist/

notifications:
  email: false
